version: "3.2"
services:
  mysql:
    image: mysql:8.0.19
    ports:
      - "3307:3306"
    env_file: .env
  php:
    build: php
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - ../API:/var/www/API:cached
      - ./logs/API:/var/www/API/var/logs:cached